In [15]:
import pandas as pd
import numpy as np
from sklearn.metrics import recall_score, precision_score

In [6]:
# 3nd labeling of test images as human performance
label = pd.read_csv('/Users/wenbo/Desktop/test_newmm.csv')

# 2nd labeling of the whole dataset as ground truth
alllab = pd.read_csv('/Users/wenbo/Desktop/crop_mm_relabel.csv') 

# prediction on test images as CNN performance
result = pd.read_csv('/Users/wenbo/Desktop/mm_result.csv')

# 1nd labeling of the whole dataset as pre ground truth
alllab_pre = pd.read_csv('/Users/wenbo/Desktop/1st_label.csv')

In [7]:
alllab

      Unnamed: 0  External ID  partialm  offcenterm  badshape  badsurface
0              0   IMG756.jpg         0           0         0           0
1              1    IMG20.jpg         0           0         1           1
2              2   IMG788.jpg         0           0         0           0
3              3    IMG52.jpg         0           0         1           1
4              4   IMG820.jpg         1           0         0           0
5              5    IMG84.jpg         1           0         1           0
6              6   IMG852.jpg         1           1         1           0
7              7   IMG116.jpg         0           1         1           0
8              8   IMG884.jpg         0           1         0           1
9              9   IMG148.jpg         0           0         0           0
10            10   IMG916.jpg         1           1         0           0
11            11   IMG180.jpg         1           1         0           0
12            12   IMG948.jpg         1           0         1           0
13            13   IMG212.jpg         1           0         0           0
14            14   IMG980.jpg         1           0         0           0
15            15   IMG244.jpg         0           0         0           0
16            16  IMG1012.jpg         0           0         1           0
17            17   IMG276.jpg         1           0         0           0
18            18  IMG1044.jpg         1           0         1           0
19            19   IMG308.jpg         1           0         0           0
20            20  IMG1076.jpg         1           0         1           1
21            21   IMG340.jpg         0           1         0           0
22            22  IMG1108.jpg         0           0         0           0
23            23   IMG372.jpg         1           0         0           0
24            24  IMG1140.jpg         1           0         0           0
25            25   IMG404.jpg         1           0         0           0
26            26  IMG1172.jpg         1           0         1           0
27            27   IMG436.jpg         1           0         1           1
28            28  IMG1204.jpg         1           1         1           0
29            29   IMG468.jpg         0           0         0           0
...          ...          ...       ...         ...       ...         ...
1306        1307   IMG945.jpg         1           1         0           0
1307        1308   IMG209.jpg         1           1         0           1
1308        1309   IMG977.jpg         0           0         0           0
1309        1310   IMG241.jpg         1           0         1           0
1310        1311  IMG1009.jpg         1           0         0           0
1311        1312   IMG273.jpg         0           1         0           0
1312        1313  IMG1041.jpg         0           0         1           0
1313        1314   IMG305.jpg         0           1         0           0
1314        1315  IMG1073.jpg         1           0         1           0
1315        1316   IMG337.jpg         1           1         0           0
1316        1317  IMG1105.jpg         1           1         1           0
1317        1318   IMG369.jpg         0           0         1           0
1318        1319  IMG1137.jpg         1           0         0           0
1319        1320   IMG401.jpg         0           0         1           0
1320        1321  IMG1169.jpg         1           1         0           0
1321        1322   IMG433.jpg         0           0         0           0
1322        1323  IMG1201.jpg         1           1         0           0
1323        1324   IMG465.jpg         0           0         1           0
1324        1325  IMG1233.jpg         1           0         1           0
1325        1326   IMG497.jpg         0           1         1           0
1326        1327  IMG1265.jpg         0           0         0           0
1327        1328   IMG529.jpg         0           0         1           0
1328        1329  IMG1297.jpg         0           1         0           0
1329        1330   IMG561.jpg         1           0         1           0
1330        1331  IMG1329.jpg         0           0         0           0
1331        1332   IMG593.jpg         1           1         0           0
1332        1333   IMG625.jpg         1           1         0           0
1333        1334   IMG657.jpg         1           1         1           1
1334        1335   IMG689.jpg         1           0         0           0
1335        1336   IMG721.jpg         1           1         1           1

[1336 rows x 6 columns]

In [8]:
label.set_index('External ID', drop = True, inplace = True)
label.drop('Unnamed: 0', axis = 1, inplace = True)
label.sort_values('External ID', inplace = True)
label.head()

             partialm  offcenterm  badshape  badsurface
External ID
IMG1003.jpg         1           0         0           0
IMG1006.jpg         1           0         0           0
IMG1009.jpg         1           0         0           0
IMG1035.jpg         1           0         1           0
IMG1038.jpg         1           0         1           1

In [9]:
alllab.set_index('External ID', drop = True, inplace = True)
alllab.drop('Unnamed: 0', axis = 1, inplace = True)
alllab = alllab.loc[label.index.values.tolist()]
alllab.head()

             partialm  offcenterm  badshape  badsurface
External ID
IMG1003.jpg         1           0         0           0
IMG1006.jpg         1           0         0           0
IMG1009.jpg         1           0         0           0
IMG1035.jpg         1           0         1           0
IMG1038.jpg         1           0         1           1

In [18]:
Y_test = np.asarray(alllab)
y_pred = np.asarray(label)
rec = recall_score(Y_test.flatten(), y_pred.flatten(), average = 'binary')
pre = precision_score(Y_test.flatten(), y_pred.flatten(), average = 'binary')
pre,rec

(0.7478991596638656, 0.9128205128205128)

In [150]:
alllab_pre.set_index('External ID', drop = True, inplace = True)
alllab_pre.drop('Unnamed: 0', axis = 1, inplace = True)
alllab_pre = alllab_pre.loc[label.index.values.tolist()]
alllab_pre.head()

             partialm  offcenterm  badshape  badsurface
External ID
IMG1003.jpg         1           0         0           0
IMG1006.jpg         1           0         0           0
IMG1009.jpg         1           1         0           0
IMG1035.jpg         1           0         1           0
IMG1038.jpg         1           0         0           1

In [151]:
result.sort_values('External ID', inplace = True)
result.set_index('External ID', drop = True, inplace = True)
result.head()

             partialm  offcenterm  badshape  badsurface
External ID
IMG1003.jpg         1           0         1           0
IMG1006.jpg         1           0         1           0
IMG1009.jpg         1           0         0           0
IMG1035.jpg         1           0         0           0
IMG1038.jpg         1           0         0           0

In [152]:
# accuracy of model
(result == alllab).sum().sum()/label.size

0.75

In [153]:
# accuracy of human
(label == alllab).sum().sum()/label.size

0.8563432835820896

In [154]:
# accuracy of pre label, how much ground truce changed between the two labeling after cropping images
(alllab_pre == alllab).sum().sum()/label.size

0.8768656716417911